# Generated by Django 5.2.9 on 2025-12-10 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shoulder_angle",
                    models.FloatField(help_text="Shoulder rotation angle"),
                ),
                ("hip_rotation", models.FloatField(help_text="Hip rotation angle")),
                ("knee_flexion", models.FloatField(help_text="Knee flexion angle")),
                ("spine_angle", models.FloatField(help_text="Spine inclination angle")),
                (
                    "ai_feedback",
                    models.TextField(blank=True, help_text="Generated advice from LLM"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
