# Generated by Django 5.2.9 on 2025-12-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="angular_momentum",
            field=models.FloatField(
                default=0.0, help_text="Estimated Angular Momentum"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="physics_score",
            field=models.FloatField(
                default=0.0, help_text="Overall Swing Efficiency Score (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="x_factor",
            field=models.FloatField(default=0.0, help_text="Shoulder-Hip separation"),
        ),
    ]
