# Generated by Django 5.2.9 on 2025-12-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_analysisresult_angular_momentum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="feedback_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="feedback/images/"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="feedback_video",
            field=models.FileField(blank=True, null=True, upload_to="feedback/videos/"),
        ),
    ]
