# Generated by Django 6.0.1 on 2026-01-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysisresult_feedback_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='downswing_time_s',
            field=models.FloatField(blank=True, help_text='Estimated downswing duration (seconds)', null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='evaluation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='omega_peak',
            field=models.FloatField(blank=True, help_text='Estimated peak angular velocity (rad/s)', null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='swing_tempo_ratio',
            field=models.FloatField(blank=True, help_text='Backswing:Downswing ratio', null=True),
        ),
    ]
