# Generated by Django 5.2.9 on 2025-12-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="basal_metabolic_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bmi",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="body_fat_percentage",
            field=models.FloatField(
                blank=True, help_text="Body Fat Percentage", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="body_water_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bone_mineral_density",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="flexibility",
            field=models.FloatField(
                blank=True, help_text="Sit and reach in cm", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="skeletal_muscle_mass",
            field=models.FloatField(
                blank=True, help_text="Skeletal Muscle Mass in kg", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="visceral_fat_level",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
